### ISSUE TITLE
Issue while transfering item with Refined Storage

### ISSUE THREAD

**Issue by Moustik2002** [jaquadro/StorageDrawers#303] opened 2016-06-18 21:50 UTC
Crash issue :

Here is the log : http://pastebin.com/8mQ1jvhV

**Comment by jaquadro** [comment] 2016-06-23 04:08
Please provide more information.  Is this producible in single player or is it a multiplayer issue?

What is "transfering an item"?  I'm not familiar with Refined Storage, so please show your setup and how you're using it.  Is a crash always reproducible?

**Comment by Moustik2002** [comment] 2016-06-30 16:20
Hi, sorry about the delay. it's a single player world. Actually Refined Storage is an AEish system, there is a storage controller linked to a drawer controller.

**Comment by raoulvdberge** [comment] 2016-07-03 13:19
This is how I'm using the API, I don't think I'm doing something wrong, but it's possible:

https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/refinedstorage/tile/externalstorage/DrawerStorage.java

**Comment by Moustik2002** [comment] 2016-07-03 16:56
i've talk about this issue to the dev here  http://minecraft.curseforge.com/projects/refined-storage?gameCategorySlug=mc-mods&projectID=243076#c201 

Maybe you should talk to him ? I'm sadly not a dev, so i'm unable to help you on this point. Anyway keep going on your very helpfull mod !

**Comment by jaquadro** [comment] 2016-07-03 19:43
The problem is probably not related to the integration code in Refined Storage.  It's a client rendering error, and one that suggests data may not have synced with the client, though I can't figure out how that particular line is able to crash.

@Moustik2002 please include a screenshot of your setup that is causing the crash, and tell me how often it's crashing or how you interact with your setup to cause it to crash.  I played around with some of the RS blocks but I'm not seeing problems.

**Comment by jaquadro** [comment] 2016-08-15 04:28
I think this is definitively fixed in the latest version.

**Closed as completed by jaquadro** 2016-08-15 04:28 UTC
Labels: Waiting
