### ISSUE TITLE
[1.11.2] Game crashes while batching chunks

### ISSUE THREAD

**Issue by PearlCanopus** [jaquadro/StorageDrawers#547] opened 2017-08-02 10:42 UTC
I use Storage Drawers alongside with several tech and informational mods and I don't really know which mod causes the game crash yet. Some indicators depend on Storage Drawers mod and anywhere I have to start to report.

Storage Drawers: 4.2.10 for MC 1.11.2
Chameleon: 3.1.0 for MC 1.11.2
Forge: 13.20.1.2386 for MC 1.11.2
CodeChickenLib: 3.0.0.284 for MC 1.11.2
Chisel: 0.0.13.22 for MC 1.11.2

The crash log shows a "crash while batching chunks" in conjunction with CodeChickenLib.
So I removed at least all mods depending on the library except NEI and CodeChickenLib itself.

With all mods loaded I get the crash while loading the savegame after building a bigger amount of drawers and trims.
Removing some of my usual suspected mods leaving me with strange rendered Storage Drawers blocks but loaded savegame finally.
Several (Compacting) Drawers (but also Bibliocraft bookshelves close to them) show up rotated 90° counter clockwise. Thermal Dynamics flux pipes have cutted their connections to each other behind rotated drawers. Framed Trims loose their chiseled block look until I break and replace them.
Of curse it also could be related to Chisel Mod too. But there were no problems until I built storage drawers into my house created with chsieled bricks and planks a longer time ago.

Do I correct all placement with a hammer, save the game and reload, all the weird behaviour reappears. After some minutes of gameplay or leaving and reentering the chunk with Storage Drawers built in, the game crashes again.
It's independent of a built controller or any piping. Building Compacting Drawers seems ok, but it may depend on the count of blocks. After building regulary wooden drawers, the problem appears faster.

My Intel-i5-3GHz-Quadcore-PC has 8G RAM installed, what never was a problem with the LitW-Modpack 1.7.10
I disabled all fancy graphics, use no shaders, no dynamic lights (OptiFine latest). Nothing changes.
Playing with F3-menu open shows up no RAM overflow before the game crashes. So I think it's not hardware related.

In a next step I will check that out with replaced storage drawers but with the recently removed mods back again.

**Comment by PearlCanopus** [comment] 2017-08-07 13:29
I need a really long time removing and readding mods.
Finally I found the reason in Pam's Harvestcraft. Thx 2 Team CoFH for the hint.

Tag BATCHING CHUNKS
There are no dependencies to Harvestcraft visible in the crash-log. But several blocks like the Presser will cause interoperability problems while rendering blocks, if i.e. the Thermal Expansion Redstone Furnace is present too.

After removing the Presser from the chunk, all is fine again. So this issue is no Storage Drawers issue and might be closed.

**Comment by jaquadro** [comment] 2017-09-06 04:05
Thanks for confirming.  There is a long history of problems with Harvestcraft, but this should finally be fixed in the most recent Harvestcraft release.  Assuming it's caused by the same tile shenanigans.

**Closed as completed by jaquadro** 2017-09-06 04:05 UTC
