### ISSUE TITLE
[1.7.10] SMP - Crash when trying to access a drawer locked with Personal key (CoFH)

### ISSUE THREAD

**Issue by eranor** [jaquadro/StorageDrawers#257] opened 2016-03-28 19:41 UTC
Hi. 

I've locked my drawer with the Personal key (CoFH) and now when I any time right click it i crash.
I'm the server owner if I've seen right I should have permission. I have tried to add myself to my friend list but it doesn't help. 
- Storage Drawers version: 1.7.10-1.9.4
- CoFH Core version: [1.7.10] 3.1.2-325
- CoFH Lib version: [1.7.10] 1.2.3-181
- ThermalFoundation version: [1.7.10] 1.2.3-112
- Forge version: 10.13.4.1614

Crash Report: [http://pastebin.com/Jhtt0Gdg](http://pastebin.com/Jhtt0Gdg)

Update:
- managed to unlock it with clicking on the drawer controller. Tried with both Personal keys, as OP or not it unlocks them.

**Comment by jaquadro** [comment] 2016-03-29 04:46
This should be fixed in 1.9.5.  It won't crash clients anymore.  I'm not 100% certain the friend functionality works because I can't test it right now, but you can try it.

I wasn't able to reproduce non-owners being able to unlock through the controller.

**Closed as completed by jaquadro** 2016-03-29 04:46 UTC
Labels: Bug, Fixed in Dev

**Comment by eranor** [comment] 2016-03-31 18:44
It' working as intended. Thank you for the fix.
