### ISSUE TITLE
[Bug] Game crashes when trying to add Environmental Tech Basalt to 1x1 storage drawer.

### ISSUE THREAD

**Issue by gkuba** [jaquadro/StorageDrawers#352] opened 2016-10-29 03:09 UTC
When ever I try to add the Environmental Tech Basalt to a storage drawer of any type /  wood type it crashes to desktop with the following crash log. 

http://pastebin.com/im1gW0N3

**Comment by jaquadro** [comment] 2016-10-29 04:25
The problem is fixed in code now.  It will be in the next release.

**Comment by jaquadro** [comment] 2016-10-29 05:44
This should be fixed in 3.3.0.

**Closed as completed by jaquadro** 2016-10-29 05:44 UTC
Labels: Bug, Fixed in Dev

**Comment by gkuba** [comment] 2016-10-29 07:17
Thanks, we will give it a try.
