### ISSUE TITLE
[Botania] Mana Tablets

### ISSUE THREAD

**Issue by EchoingZen** [jaquadro/StorageDrawers#193] opened 2016-01-14 23:51 UTC
Placing Mana Tablets in a Storage Drawer appears to strip the bar from the tablet.  A possible explanation was given by lazersmoke on reddit.

"The problem is that the storage drawer makes the mana tablet lose its damage value, which makes it think it is creative (thus no mana bar), but its actually still a normal mana tablet. I would file a bug report here. and tell them they aren't preserving the damage values of mana tablets."

Some of my tablets have this, some do not.  It may be related to logging out when they are in a drawer.

(Regrowth modpack, FYI)

**Comment by jaquadro** [comment] 2016-01-15 01:09
Drawers should always be preserving damage values.  But maybe there's something special with tablets.  I'll need to look.

**Comment by codewarrior0** [comment] 2016-01-15 01:17
I'm playing the regrowth pack right now, so I gave it a try.

Cannot confirm, mana tablets keep their damage bars after going into and out of a drawer.

However, I remember that in the early botania quests that give mana tablets as a reward, those tablets do not have damage bars. The damage bars appeared on them some time later, but I'm not sure when. Maybe when I relogged?

**Comment by EchoingZen** [comment] 2016-01-15 01:43
I just reproduced it.

Step one: Fill a tablet to full.
Step two: put the full tablet (with damage bar) into a storage drawer.
Step three: quit Minecraft
step four: open Minecraft
Step five: pull out the tablet with no bar.

**Comment by jaquadro** [comment] 2016-01-15 01:45
When if you don't quite fill it?
And what happens when you try using the tablet after you remove it?

**Comment by EchoingZen** [comment] 2016-01-15 01:48
If you don't quite fill it.. its fine.  I can take them out after relogging and everything appears normal.  I believe it only affects full tablets.  I haven't tested empty tablets.

**Comment by codewarrior0** [comment] 2016-01-15 01:59
> I just reproduced it.

Did the same thing and reproduced it here. I just did some testing with MCEdit:

A full mana tablet (500k mana) normally has Damage=1.

After doing the steps you gave, the full mana tablet pulled from the drawer has Damage=0.

**Comment by jaquadro** [comment] 2016-01-15 02:18
So, the drawer indeed writes out a 0 damage value on NBT save.  But the prototype stack stored within the drawer itself has the correct damage value of 1.

Vakii has an inconsistency in the mana tablet implementation.  The item overrides the getDamage() accessor, and scales the internal mana value (range 0 - 500,000) to a damage value in the range (0 - 1000).  If the mana is completely full, it calculates an inconsistent damage value of 0.  This needs to be brought up there.

**Comment by codewarrior0** [comment] 2016-01-15 02:19
That would explain why the HQM quest rewards seem to have the same problem!

**Comment by EchoingZen** [comment] 2016-01-15 02:21
I'll make a report to Vazkii then :)

**Comment by blacksmithgu** [comment] 2016-01-15 21:54
A solution to this problem was merged a little while ago, and just involved removing damage values entirely in favor of using other methods for showing the durability bar. I tested with storage drawers after the patch and it seems to be in order now.

**Closed** 2016-01-16 01:44 UTC
Labels: Compatibility
