### ISSUE TITLE
Snow/Snowballs in compacting drawer

### ISSUE THREAD

**Issue by kronski** [jaquadro/StorageDrawers#275] opened 2016-04-30 08:48 UTC
When I input snowballs and snow in compacting drawer it seems to act really wierd.
It doesn't respect the 16 item limit on the snowballs. I don't know if it dupes the items but I can retrieve snowball with stacksize 64.

**Comment by jaquadro** [comment] 2016-05-15 03:06
What version?  I tested this on 1.7.10 but I can't reproduce it.  Stack size of 16 is respected.

**Comment by kronski** [comment] 2016-05-15 05:10
Hi.

I had problems with the snowballs when it was connected with logistics
pipes mod. It was with the ftb infinity evolved modpack latest for 1.7.10
v1.5 I think.

Best regards
Anders

**Comment by ChickenDuck** [comment] 2016-12-01 13:59
MC: 1.7.10
mod list:
CodeChickenCore-1.7.10-1.0.7.47-universal
NotEnoughItems-1.7.10-1.0.5.120-universal
StorageDrawers-1.7.10-1.10.7
Waila-1.5.10_1.7.10

Step to reproduce:
1. Put more than 4 stacks of Snow (not Snowball) into a Compacting Drawer
2. Take out a Snowball
3. Put the Snowball back to the Compacting Drawer
4. You notice the snow ball didn't go into, instead turns into the amount of excessive snowballs above 4 stacks of Snow
Note: The more Snow you put into the Compacting Drawer, the more snowballs it create in your hand. If you insert 6 stacks of Snow, you will then have a stack of 768 snowballs

**Comment by ChickenDuck** [comment] 2016-12-04 17:05
@jaquadro (mention you here in case you missed the notification)
This issue still exist in current 1.10 version

8 stacks of snow
![2016-12-05_00 52 48](https://cloud.githubusercontent.com/assets/8293704/20867741/4f60ccb4-ba86-11e6-981f-735aa49c4342.png)
Take 1 snowball out
![2016-12-05_00 52 51](https://cloud.githubusercontent.com/assets/8293704/20867742/60033c6e-ba86-11e6-9cff-4afd0eb2117f.png)
Put it back in
![2016-12-05_00 52 56](https://cloud.githubusercontent.com/assets/8293704/20867743/6272bb28-ba86-11e6-9e93-e831558e3272.png)

**Comment by jaquadro** [comment] 2016-12-05 06:26
Okay, I was able to reproduce it.  Still need to look into the root cause.

**Comment by jaquadro** [comment] 2016-12-06 05:36
Fixed in 3.5.7

**Closed as completed by jaquadro** 2016-12-06 05:36 UTC
Labels: Bug
