### ISSUE TITLE
Can't Make a basic Birch Drawer

### ISSUE THREAD

**Issue by PokeMaserJ** [jaquadro/StorageDrawers#305] opened 2016-06-21 14:45 UTC
MC Version: 1.9.4
Mod Version: StorageDrawers-1.9-3.1.7

How to reproduce: Try to craft a Basic Birch Drawer

What I expect to happen: Get a Basic Birch Drawer

What actually happens: Get a Basic Oak Drawer

**Comment by codewarrior0** [comment] 2016-06-21 14:49
I think this is fixed in 3.1.8. Can you confirm?

**Comment by PokeMaserJ** [comment] 2016-06-21 17:07
Doesn't seem to be

**Comment by jaquadro** [comment] 2016-06-22 03:24
This doesn't reproduce for me, but I bet it's related to fallback recipes.  I'd ask you to disable that in config, but that configuration is being ignored.  I'm also not using fallback recipe objects for some reason.  Seems to be an overall regression.

Tentatively fixed in dev.  When the next version is released, you can see if that fixes is.

**Comment by jaquadro** [comment] 2016-06-25 03:15
Should be fixed in 3.1.10.  Re-open if that's not the case.

**Closed as completed by jaquadro** 2016-06-25 03:15 UTC
Labels: Fixed in Dev

**Comment by codewarrior0** [comment] 2016-09-18 11:14
FYI, there is a known issue with Brad's Backpacks mod that can cause this problem. 

Backpacks will re-sort the recipe list, but it does not honor the Forge recipe sorting rules while doing so. A config option in Backpacks will stop it from doing this.

**Comment by PokeMaserJ** [comment] 2016-09-18 16:48
So would that config be the "B:Disable_recipe_sorting? And if so should it be true or false?

**Comment by codewarrior0** [comment] 2016-09-18 17:20
True.
