### ISSUE TITLE
drawers not being defined correctly

### ISSUE THREAD

**Issue by benbenlaw** [jaquadro/StorageDrawers#934] opened 2021-03-11 13:44 UTC
https://github.com/TeamPneumatic/pnc-repressurized/issues/759

**Comment by desht** [comment] 2021-03-11 14:03
Note: this should be as simple as adding: 
```java
@Override
public boolean allowsMovement(BlockState state, IBlockReader worldIn, BlockPos pos, PathType type) {
      return false;
}
```
to your `BlockDrawers` class.  The issue is that drawers appear to have a non-full but movement-blocking collision shape, but don't override this method.  So entities think they can pathfind through them, when they can't.  This is particularly noticeable with PneumaticCraft drones, which tend to find this problem very frequently!

(You'll notice that many non-solid vanilla blocks also override this method to return false, for this very reason)

**Comment by jaquadro** [comment] 2021-12-21 04:37
Fixed in the latest 1.16 release

**Closed as completed by jaquadro** 2021-12-21 04:37 UTC
