### ISSUE TITLE
Items put out of storage drawers and then bug through the floor

### ISSUE THREAD

**Issue by Beerfazz** [jaquadro/StorageDrawers#476] opened 2017-05-14 21:58 UTC
youtu.be/3m7fKOYni3o
Apparently, if you try to get items out of storage drawers that are directly above the floor but you have a full inventory, they pop out and seem to bug one block through it (on 2x2 and 1x1, I haven't tested others). So if the floor is 2 blocks thick, they get back to the top. But if there is e.g. void below as shown in the clip, they fall through the floor. Only happens when the drawer is one layer above the floor.

**Comment by jaquadro** [comment] 2017-06-06 04:55
This is possibly fixed in 3.7.8/4.2.8.  I raised the spawn height a bit, so hopefully that is enough to prevent any clipping.  I couldn't reproduce clipping with the original height in testing, however.

**Closed as completed by jaquadro** 2017-06-06 04:55 UTC
Labels: Fixed in Dev
