### ISSUE TITLE
[1.3.5] Drawers don't sync correctly when coming back from the nether

### ISSUE THREAD

**Issue by hvdklauw** [jaquadro/StorageDrawers#54] opened 2015-04-02 20:12 UTC
I've added Storage Drawers to my Resonant Rise 3.2.4.3 installation. Whenever I go to the nether and come back all my drawers won't sync with the client correctly anymore. 

sometimes I can add items but can't get them out and sometimes I can get infinite amount out but can't get anything in.

**Comment by jaquadro** [comment] 2015-04-02 20:15
Are you by any chance in adventure mode?

**Comment by Cracks777** [comment] 2015-04-02 20:16
ive had this in survival mode, wondered what caused it, but yes coming back from the nether is the cause

**Comment by jaquadro** [comment] 2015-04-02 23:21
Can you tell me if this is in SSP or SMP or both?

**Comment by Cracks777** [comment] 2015-04-02 23:29
ive only noticed it on my server, as i dont play single player

**Comment by jaquadro** [comment] 2015-04-03 00:22
Could either of you provide any more information?  A clear way to reproduce, how often it occurs?

I did some basic client/server testing, and going to the Nether and back did not affect how they operated.

**Comment by Cracks777** [comment] 2015-04-03 01:31
i thik this may have been fixed in the newer builds, as i cannot get it to happen anymore, ill keep testing.

**Comment by jaquadro** [comment] 2015-04-29 20:45
I haven't heard anything on this for a while, so I'm going to assume it hasn't come up.  You can re-open the issue if it's still a problem.

**Closed by jaquadro** 2015-04-29 20:45 UTC
