### ISSUE TITLE
Framing Table contents do not appear at certain viewing angles.

### ISSUE THREAD

**Issue by Drullkus** [jaquadro/StorageDrawers#300] opened 2016-06-17 23:15 UTC
Mod Filename - StorageDrawers-1.9-3.1.7

Modpack - FTB Unstable 4.0.7

See Gfycat - https://gfycat.com/OnlyAgileIndianskimmer

When I look to the right, the Framing Table's (which is on the left when I'm looking to the right) world inventory disappears.

![https://gfycat.com/OnlyAgileIndianskimmer](https://thumbs.gfycat.com/OnlyAgileIndianskimmer-size_restricted.gif)

**Comment by jaquadro** [comment] 2016-06-18 03:42
Probably just need to tweak the bounding box on the TE.

.... is the block on the left partially embedded and hanging off the table?

**Comment by Drullkus** [comment] 2016-06-18 21:25
It's part of the fancy display rendering of the table.

**Comment by jaquadro** [comment] 2016-06-23 04:12
I've tried looking at the table from all kinds of angles, but I can't reproduce this.  Does this happen for you if you run the mod by itself?

**Comment by Drullkus** [comment] 2016-06-25 06:22
I'll have to test it. o.O

**Comment by jaquadro** [comment] 2016-11-22 05:56
Well, I finally saw this happen.  Based on the bug it would be dependent on your position in the world.  Fixed in 3.4.7.

**Closed as completed by jaquadro** 2016-11-22 05:56 UTC
Labels: Can't Reproduce

**Comment by Drullkus** [comment] 2016-11-22 06:12
\o/
