### ISSUE TITLE
[1.7.10] When connected with Thermal Dynamics server crashes

### ISSUE THREAD

**Issue by GameBurrow** [jaquadro/StorageDrawers#309] opened 2016-07-11 09:31 UTC
https://openeye.openmods.info/crashes/9e66b74d4379c4418c0dbc0d795d351e

We have a problem that server won't start up since last night. I imagine there is some kind of incompatiblity between Storage Drawers and TD.

When taking Storage Drawers out the server starts again. Sadly I don't know what setup is causing the issue as we cannot see the world when TD is in.

**Comment by kerts93** [comment] 2016-07-11 09:32
https://github.com/CoFH/Feedback/issues/1204

**Comment by GameBurrow** [comment] 2016-07-11 11:13
When taking the world to Singleplayer, we recive the same issue:
https://openeye.openmods.info/crashes/b85c66c530b91e1008cc4d7fca846286

We have an idea that it could be TD servos trying to take items out of empty drawers

**Comment by jaquadro** [comment] 2016-08-04 04:10
As TD is closed source and I have no working knowledge of its internal workings, this is almost impossible to debug without a 100% reliable repro case.  The closing comment in the attached TD thread isn't very useful to me.  But it suggests to me that the problem is happening between TD and a controller block.

Controllers can change the number of slots they report if the composition of the network changes, but it should never happen in the middle of another mod interacting with the inventory within the same tick.  If TD cached slot information between ticks, then there could be a problem.

You could try disabling the controller block in the mod settings, which will remove all instances of it from the world, and see if that stops the problem.

**Comment by GameBurrow** [comment] 2016-08-04 16:14
We bybassed the issue by reseting the TD mod (removing mod and readding it, which cleared it from the world), sadly we couldn't pinpoint the exact location as nothing reports about the location, thus we couldn't find the excat setup that causes this.

**Comment by GameBurrow** [comment] 2016-08-06 13:42
@jaquadro if we can confirm that the issue is controller block, does this help you in any way (I'll try it today)? Can you fiqure some kind of fix or bybass?

**Comment by jaquadro** [comment] 2016-08-06 17:05
I'm not sure it helps me find a fix.  But it gives you the option of living without the controller block if that's what will keep the two mods working in harmony.

**Comment by GameBurrow** [comment] 2016-08-08 17:41
@jaquadro Here is a interesting thing I found.

I accidentally removed Controller slaves instead of controllers and the world I sent you starts up every time. Could the controller slaves be a issue instead?

**Comment by jaquadro** [comment] 2016-08-08 17:46
Seems unlikely, but you could monitor things for a while.  The very nature of the problem I'm sure requires some time to pass before it occurs.

**Closed as completed** 2020-04-16 07:58 UTC
