### ISSUE TITLE
[1.14.4] East/west-facing drawers inverted

### ISSUE THREAD

**Issue by Thorf13** [jaquadro/StorageDrawers#730] opened 2019-09-09 00:49 UTC
Not a crash, so there's no log. And thanks for an amazing job converting Storage Drawers to 1.14.4!

I'm finding that north/south-facing drawers work perfectly, but two by two drawers placed facing east/west are inverted horizontally. So anything placed in the top right drawer appears in the top left, and can be withdrawn by clicking in the top left. And vice versa.

I'm sorry, I haven't had a chance to test more. I will update with more information later on if it helps.

**Comment by jaquadro** [comment] 2019-09-09 13:37
I wonder if this is something I broke at the last minute because I definitely tested all directions.  Will take another look.

**Comment by jaquadro** [comment] 2019-09-10 03:46
I was still unable to reproduce in my latest build

**Comment by Thorf13** [comment] 2019-09-10 05:22
I will check in the new version and see if it's still happening to me.

**Comment by srafaorasp** [comment] 2019-09-11 17:48
I can confirm this tho i don't know exactly what it is doing. what i see it doing for me is N S facing drawers are shifted by one to the right (2x2 birch and dark wood tested) E W facing drawers are working fine for me.   
Forge version  1.14.4-28.0.88
Mod version 1.14.4-6.0.3
Any and all info you need available upon request. 

PS thank for the good work. this is a must have mod for me.

**Comment by jaquadro** [comment] 2019-09-12 06:45
Finally figured it out, and it depended on what map quadrant you were in (ugh).

Should now be fixed in 6.0.4.

**Closed as completed by jaquadro** 2019-09-12 06:45 UTC
